apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-sync
subjects:
- kind: ServiceAccount
  name: ns-reconciler
  namespace: config-management-system
roleRef:
  kind: Role
  name: tenant-sync
  apiGroup: rbac.authorization.k8s.io